version: '3.7'
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=lms_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres