CREATE TABLE IF NOT EXISTS "_users" (
    "id" BIGSERIAL PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP DEFAULT NULL,
    "first_name" VARCHAR(255) DEFAULT NULL,
    "last_name" VARCHAR(255) DEFAULT NULL,
    "phone" VARCHAR(255) UNIQUE,
    "password" VARCHAR(255),
    "profile_image" TEXT DEFAULT NULL,
    "is_block" BOOLEAN DEFAULT false,
    "block_by_id" INT DEFAULT NULL,
    "block_date" TIMESTAMP DEFAULT NULL,
    "block_reason" TEXT DEFAULT NULL,
    "last_login_date" TIMESTAMP DEFAULT NULL,
    "role_id" INT DEFAULT NULL,
    "bio" TEXT DEFAULT NULL,
    "resume_file" TEXT DEFAULT NULL,
    "salary_amount" DECIMAL DEFAULT 0,
    "email" VARCHAR(255) DEFAULT NULL,
    "national_id" VARCHAR(255) DEFAULT NULL,
    "is_verified" BOOLEAN DEFAULT FALSE,
    "verified_date" TIMESTAMP DEFAULT NULL,
    "verified_by_id" INT DEFAULT NULL,
    "is_profile_complete" BOOLEAN DEFAULT FALSE
)