openapi: 3.0.0
info:
  title: Learning Management System API
  version: 1.0.0
servers:
  - url: http://localhost:8081/api
paths:
  /roles:
    post:
      responses:
        201:
          description: Role Created Successfully
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/CreateRoleResDTO'
        401:
          description: Unauthorized
        409:
          description: Conflict Role Name
        500:
          description: Internal Server Error
      summary: Create Role
      tags:
        - roles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoleReqDTO'
    get:
      summary: Get Roles
      tags:
        - roles
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          schema:
            type: integer
      responses:
        200:
          description: Get Roles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRolesDTO'
  /roles/{id}:
    delete:
        tags:
          - roles
        summary: Delete Role By ID
        parameters:
          - name: id
            in: path
            required: true
            description: Role Id
            schema:
              type: integer
        responses:
          200:
            description: Role Deleted Successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/DeleteRoleResDTO'
          400:
            description: Role Deleted Before
          404:
            description: Role Not Found
          500:
            description: Internal Server Error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RoleItem:
      type: object
      properties:
        id:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        name:
          type: string
        createdById:
          type: integer
        lock:
          type: boolean
        permissions:
          type: array
          items:
            type: string
    CreateRoleReqDTO:
      type: object
      properties:
        name:
          type: string
        permissions:
          type: array
          items:
            type: string
    CreateRoleResDTO:
      type: object
      properties:
        statusCode:
          type: integer
        data:
          type: object
          properties:
            role:
              $ref: '#/components/schemas/RoleItem'
    GetRolesDTO:
      type: object
      properties:
        data:
          type: object
          properties:
            rows:
              type: array
              items:
                $ref: '#/components/schemas/RoleItem'
            totalPage:
              type: integer
            currentPage:
              type: integer
            totalCount:
              type: integer
        statusCode:
          type: integer
    DeleteRoleResDTO:
      type: object
      properties:
        data:
          type: object
          properties:
            message:
              type: string
        statusCode:
          type: integer
security:
  - BearerAuth: []